included:
  - Sources

identifier_name:
  min_length: 1
  max_length: 60

type_body_length:
  warning: 600
  error: 800

file_length:
  warning: 700
  error: 1000

function_body_length:
  warning: 100
  error: 250

function_parameter_count:
  warning: 8
  error: 10

large_tuple:
  warning: 4

line_length:
  warning: 150
  error: 200
